name: CVScoreboards
main: org.cubeville.cvscoreboards.CVScoreboards
author: ToeMan_
version: 1.20
api-version: 1.20
depend: [CVTools]
softdepend: [PlaceholderAPI]

commands:
  cvscoreboards:
    aliases: sidebar
    permission: cvscoreboards.admin

permissions:
  cvscoreboards.admin:
    description: Gives player access to every CVScoreboards command
    default: op